### ISSUE TITLE
Fully support IMS headers

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/jain-sip#105]
https://tools.ietf.org/html/rfc3455#section-5.6
Currently we just support gen-value with toke nor quotedString, but not host, so we lose capability to parse IPv6 addresses

**Comment by xhoaluu** [comment]
Hi @jaimecasero, Please help me to understand this requirement correctly:
Do you mean that in PChargingVectorHeader.java interface, I need to put some methods:

public Host getICIDGeneratedAt();
public void setICIDGeneratedAt(Host host);

public Host getOriginatingIOI();
public void setOriginatingIOI(Host origHost);

public Host getTerminatingIOI();
public voi setTerminatingIOI(HOst termHost);

And those interface need to be implemented in PChargingVector.java

Thank for your help :)

**Comment by jaimecasero** [comment]
Not exactlly..

There are a number of IMS headers which doesnt currently support full specifications in terms of parsing grammar. In particular the parameters related to IPv6 addresses are not implemented, so people wanting to use these headers with IPv6 addresses are not supported.

Taking PChargingVectorHeader example, the specifications covers an special params with "gen-value" definition. This rule coming from 3261 is:
gen-value      =  token / host / quoted-string
host             =  hostname / IPv4address / IPv6reference

So, any of these param should support IPv6. The issue is that if you try to parse such a header, there is a parsing exception,because of different expected char sets.. This issue comes from [SOIssue](http://stackoverflow.com/questions/37856517/pchargingvectorparser-of-jain-sip-ri-doesnt-accpet-ipv6-in-icid-value-of-p-charg) .There you will see and example of this parsing failure.

So, you should start by defining a unit test including this header value, to ensure is failing with current impl. Then you need to investigate the JAIN-SIP stack parsing layers, and introduce any modifications to support rule "host             =  hostname / IPv4address / IPv6reference" including IPv6. This parsing layer is complex, so take your time and feel free to ask me.

am i explaining myself?

**Comment by xhoaluu** [comment]
Hi @jaimecasero ,

It's really clear now. Thank for your help. if I have any more further question, I will ask you directly here.

**Comment by jaimecasero** [comment]
Great. The parsing layers is an intrincate class hierarchym so if you start from PChargingVectorParser, you will ge to the core classes ParserCore
