### ISSUE TITLE
SessionDescriptionImpl constructor prepends a -u corrupting the field in sdp

### ISSUE THREAD

**Issue by amitch** [RestComm/jain-sip#112]
Hello,

The SessionDescriptionImpl copy constructor prepends an -u due to bug

This is at 
https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sdp/SessionDescriptionImpl.java#L129

Looking at
https://github.com/amitch/jain-sip/blob/master/src/gov/nist/javax/sdp/fields/URIField.java

 newUF.setURI(otherUriField.toString());
should be replaced by
 newUF.set(otherUriField.get());

which will cover both URI or string being set as well as fix case of extra -u. Changing it to below fixes only -u issue.

 newUF.setURI(otherUriField.getURI());

Amit

**Comment by deruelle** [comment]
@amitch would you like to try to contribute a Pull Request fixing the code with a non regression test ?

**Comment by amitch** [comment]
Hey Jean,

Not in near term. Will wait for release if and when happens. Please add it to your roadmap as appropriate. 

There is a non trival ramp up to get jain-sip compiling locally and then trying out. 
I looked at the tests briefly, there are not granular to add new things easy.

Amit

**Comment by deruelle** [comment]
@xhoaluu @jaimecasero can you review as time permits ?

**Comment by jaimecasero** [comment]
adding test to assert on cloned sdp for verification...

**Comment by jaimecasero** [comment]
Confirmed there is a 
java.net.MalformedURLException: no protocol: u=http://www.example.com/seminars/sdp.pdf

later when the URI is actually parsed during get()... The "u=" should be removed as suggested by @amitch

**Comment by jaimecasero** [comment]
The original code mentions:

>         // URI field requires deep copy

But an URL is final in Java, so there is no way to modify the object itself. Why do we require deep copy of final objects?? -> I think we could live by reusing same object here ( this is the suggested approach from reporter)

**Comment by jaimecasero** [comment]
Patch with test on its way
