### ISSUE TITLE
UDP memory leak

### ISSUE THREAD

**Issue by knosach** [RestComm/jain-sip#159]
Faced in performance testing of SipStack build 68 http://ci.telestax.com/view/JSIP/job/TelScale-JAIN-SIP-7-Performance-UAS/68/artifact/results-dir/PerfCorderAnalysis.html

**Comment by jaimecasero** [comment]
logging level was nto properly set cuasing perf issues. After changing to ERROR level these are new results
http://ci.telestax.com/view/JSIP/job/TelScale-JAIN-SIP-7-Performance-UAS/73/

we can see proper GC times, no sip call failures, and memory graph stable, after running test, the memory is fully recoverd after explicit GC
