### ISSUE TITLE
Enhance Niohandler concurrency model

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/jain-sip#47]
On -t1 sipp test profiling a high thread contention is shown in enterIOCriticalSection, and lower but still noticeable on "selector.wakeup()"

**Comment by jaimecasero** [comment]
selector.wakeup is hardly avoidable, since we need to notify the selector thread about available data to be sent. 

Regarding enterIOCriticalSection in "send" method, i think huge enhancement could be applied using the https://en.wikipedia.org/wiki/Double-checked_locking mechanism. Currently even if the socket is available in the table, and the state is correct(open||active) the semaphore is acquired, preventing threads to write to the socket.

In addition, too many synchronize sections are in place at socketTable level, preventing good thread contention. It would be better to use concurrent collections... Locking at socketTable level is near system level, which is too much locking...

**Comment by deruelle** [comment]
Agreed. please try to implement the suggestions and see if that helps.
We can use javolution concurrent structures/collections if needed.
