### ISSUE TITLE
Question: Disable Retransmission for Reliable Transport?

### ISSUE THREAD

**Issue by valliman** [RestComm/jain-sip#68]
Is there a way in the Transaction API to disable retransmission if a reliable transport mechanism (i.e. TCP) is used. I checked through the code and it seems that I can set various timers and the retransmission interval. However that does not allow to disable the retransmission. Is this possible on a transaction base?

**Comment by jaimecasero** [comment]
Hi, sorry for the late answer. 

That level of timer configuration granularity is not currently possible.
Nervertheless, the code is aware of transport reliability when it comes to retransmissions. Look at for an exmaple..
https://github.com/RestComm/jain-sip/blob/master/src/gov/nist/javax/sip/stack/SIPClientTransactionImpl.java#L483
